In [1]:
import numpy as np
import pandas as pd

In [2]:
data_f= np.array([[1,0,1,0,0,0,0,0],
                   [1,0,0,1,0,0,0,0],
                   [0,1,1,0,0,0,0,0],
                   [0,1,0,1,0,0,0,0],
                   [0,0,0,0,1,0,1,0],
                   [0,0,0,0,1,0,0,1],
                   [0,0,0,0,0,1,1,0],
                   [0,0,0,0,0,1,0,1]])
# data_g= np.array([[1,0,0,0,0],
#                 [1,1,1,1,0],
#                 [0,0,1,1,1],
#                 [1,1,0,0,0]])
data_g= np.array([[1,1,0,0,0,0,1,1],
                   [0,0,1,1,1,1,0,0],
                   [1,1,0,0,1,1,0,0],
                   [0,0,1,1,0,0,1,1]])

In [3]:
#remove duplicate rows
unique_f = np.unique(data_f,axis=0)
unique_f
unique_g = np.unique(data_g,axis=0)
unique_g

array([[0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 0]])

In [4]:
col_sum = np.sum(data_g, axis=1)
sort_index = np.argsort(col_sum) # index sort in descending order
out_matrix = data_g[:, sort_index]
sort_index

array([0, 1, 2, 3], dtype=int64)

In [5]:
#sort the array by sum(max to min)
data_g=sorted(data_g, key=lambda x: sum(x),reverse=True)
data_g = np.asarray(data_g)
data_f=sorted(data_f, key=lambda x: sum(x),reverse=True)
data_f = np.asarray(data_f)

In [6]:
#remove super set
def remove_superset(data):
    for i in range(len(data)):
        zero_index = np.where(data[i] == 0)[0]
        if(len(zero_index) != 0):
            zero_cols = data[:, np.array(zero_index)]
            rows_sum = np.sum(zero_cols, axis=1)
            #print(zero_cols)
            #print(rows_sum)
            if 0 in rows_sum:
                np.delete(data,i,0) 
    return data      
np_f=remove_superset(data_f)
np_g=remove_superset(data_g)

In [ ]:
#sum the rows
def display(f,g):
    f=pd.DataFrame(unique_f)
    f.loc['Column_Total']= f.sum(numeric_only=True, axis=0)
    fmax_col_index = np.argmax(np.array(f.loc['Column_Total']))
    f.loc[:,'Row_Total'] = f.sum(numeric_only=True,axis=1)
    fmax_row_value=max(f['Row_Total'][0:-1])
    df_f=f
    print(df_f)
    print("the variable that appears max in f is: X",fmax_col_index)

    g=pd.DataFrame(unique_g)
    g.loc['Column_Total']= g.sum(numeric_only=True, axis=0)
    gmax_col_index = np.argmax(np.array(g.loc['Column_Total']))
    g.loc[:,'Row_Total'] = g.sum(numeric_only=True,axis=1)
    gmax_row_value=max(g['Row_Total'][0:-1])
    df_g=g
    print(df_g)
    print("the variable that appears max in g is：X",gmax_col_index)
    return df_f,df_g

In [ ]:
# m=np.array(f)[0:-1, 0:-1]
# print(m)
# a=max(f['Row_Total'][0:-1])
# print(a)

In [7]:
# Total number of rows:
np.shape(np_g)[0]

#Total number of Columns: 
np.shape(np_g)[1]


8

In [ ]:
a= np.array([[1,1,1,0,0],
             [1,1,1,1,0],
             [0,0,0,1,1],
             [0,1,0,0,0]])
# sum over rows: (a.sum(axis=1))
#np.shape(a)[0]
index=np.argmax(a.sum(axis=0))
print(index)
f0=a[a[:,index]==1]  ## select rows where spliting var column is ==1
f0[:,index]=0
f1=a[a[:,index]==0] 
dual_matrix=np.zeros((np.shape(f1)[1],np.shape(f1)[1]))  

for index, i in enumerate(f1[0]):
    if i==1:
        dual_matrix[index][index]=1
dual_matrix

In [12]:
# pre-req
#np_f and np_g are numpy arrays
check_p=1
satisfy=False
def check_pre(f,g):
# 1. assume var in f and g are the same, but we check if # of columns in f = # of columns in g 
    if np.shape(f)[1] != np.shape(g)[1]: 
        print("not dual, # of columns in f = # of columns in g")
        return False
# 2.check if largest of sum_row in f <= # of rows in g, largest value of sum_row in g <= # of rows in f 
    #a=max(f['Row_Total'][0:-1])
    fmax_sum_row=max(f.sum(axis=1))
    gmax_sum_row=max(g.sum(axis=1))
    if fmax_sum_row > np.shape(np_g[0]): #f.loc
        print("not dual, fmax_row_value > len(g)")
        return False
    #b=max(g['Row_Total'][0:-1])
    if gmax_sum_row > np.shape(np_f[0]):
        print("not dual, gmax_row_value > len(f)")
        return False
# 4. sum 2^(-|c in f|)+sum 2^(-|c in g|) >=1, where c is each sum_row value(for loop)>=1
    sum_fg=0
    f_row_sum_array=f.sum(axis=1)
    g_row_sum_array=g.sum(axis=1)
    
    for i in range (len(f)-1):
        sum_fg+=1/(2**(f_row_sum_array[i]))
    for i in range (len(g)-1):
        sum_fg+=1/(2**(g_row_sum_array[i])) 
    if sum_fg < 1:
        print("not dual, sum_fg < 1")
        return False
    
# 5. if (# of rows in f) * (# of row in g) >1
    if np.shape(f)[0]*np.shape(g)[0] <= 1:
        print("not dual, (# of rows in f) * (# of row in g) <= 1")
        return False
        
# 6. C ^ C' != empty
#     print(f'The length of f: {len(f)}')
    
    f_col_sum_array=f.sum(axis=0)
    g_col_sum_array=g.sum(axis=0)
    
    satisfy=False
    for i in range(len(f_col_sum_array)):
#         import pdb;  pdb.set_trace()
        if f_col_sum_array[i] ^ g_col_sum_array[i] == True:
            pass
        else:
            satisfy=True
            break
    return satisfy

In [19]:
#spiltting, 
#F0=rows that contains x, change the position of x to 0
#F1=rest of the rows
def split(f):
    # split function return F0, F1 or g0, g1
    index=np.argmax(f.sum(axis=0))
    f0=f[f[:,index]==1]  ## select rows where spliting var column is ==1
    f0[:,index]=0
    f1=f[f[:,index]==0]
    return f0,f1 

def check_dim(L,R):
    return (np.shape(L)[0]>1 and np.shape(R)[0]>1)

#dual_matrix=[]
def print_dual(L,R):
    if np.shape(L)[0]==1:
        dual_matrix=np.zeros((np.shape(L)[1],np.shape(L)[1]))      
        for index, i in enumerate(L[0]):
            #print(i)
            if i==1:
                dual_matrix[index][index]=1
    elif np.shape(R)[0]==1:
        dual_matrix=np.zeros((np.shape(R)[1],np.shape(R)[1]))      
        for index, i in enumerate(R[0]):
            #print(i)
            if i==1:
                dual_matrix[index][index]=1
        return dual_matrix
                
        
# e.g.: error_path = [path_0, path_1] = [['L', 'R'], ['L','L','L']]
#error_path=[]
def fk(L, R, path):
    if check_dim(L,R)==False:
        #print(f'error path is: {path}')
        a=print_dual(L,R)
        print(f'There exist a single row matrix, and the dual of it is: {a}')
        return
    
    if check_pre(L,R) == False:
        print(f'error path is: {path}')
        #error_path.append(path) 
        return
        
    else:
        f0,f1=split(L)
        g0,g1=split(R)
        L=np.concatenate((f0, f1),axis=0)
        R=g1
        print(f"path:: {path}")
        path.append("L")
        fk(L, R, path)
        L=np.concatenate((g0,g1), axis=0)
        R=f1
        path = path[0:-1]
        path.append("R")
        fk(L, R, path)
#     return error_path
    
    print("it is not dual")

In [20]:
#test fk
# path=[]
# print(type(f))
# f = np.array(f)[0:-1, 0:-1]
# g = np.array(g)[0:-1, 0:-1]
fk(np_f, np_g, path)

path:: ['L', 'L', 'L', 'L']
path:: ['L', 'L', 'L', 'L', 'L']
There exist a single row matrix, and the dual of it is: None
path:: ['L', 'L', 'L', 'L', 'L', 'R']
path:: ['L', 'L', 'L', 'L', 'L', 'R', 'L']
path:: ['L', 'L', 'L', 'L', 'L', 'R', 'L', 'L']
There exist a single row matrix, and the dual of it is: [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
There exist a single row matrix, and the dual of it is: [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
it is not dual
There exist a single row matrix, and the dual of it is: [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0

In [ ]:
# test for split function 
print(f)
index=np.argmax(np.array(f.loc['Column_Total'][:-1]))
i=np.array(f)[0:-1, 0:-1]
#print(i)
f0=i[i[:,index]!=0]
f1=i[i[:,index]==0]
f0[:,index]=0
print(f0)

In [ ]:
#test for dual printer
dual_matrix=[]
def print_dual(L,R):
    if len(L)==1:
        dual_matrix=np.zeros((len(f.columns)-1,len(f.columns)-1))      
        for index, i in enumerate(f.iloc[0]):
            if i==1:
                dual_matrix[index][index]=1
        return dual_matrix
f=f.head(1)
print(f)
print_dual(f,g)

In [ ]:
print(f)
L=f.iloc[0:-1,0:-1]
#R=g[0:-1, 0:-1]
print(len(L))

In [ ]:
np.zeros(5)